# Generated by Django 2.2.1 on 2019-06-21 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='moviecollection',
            name='poster',
            field=models.CharField(blank=True, max_length=2048, null=True),
        ),
        migrations.AddField(
            model_name='moviecollection',
            name='title',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='moviecollection',
            name='year',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
    ]
